### ISSUE TITLE
Default Arguments

### ISSUE THREAD

**Issue by chankl3579** [jasminsternkopf/mel_cepstral_distance#1]
Thanks for the MCD implementation! 

I tried to run the ```get_mcd_between_wav_files``` function with the three sets of example provided and got MCD around 8-14. 
Could you please tell how the default arguments are set (e.g. based on some documents, etc.)? 
since if I change the arguments, the result MCD change quite a lot, 
e.g. if I change the argument ```n_mels``` to, like 40, the MCD would be around double. 

Also I get the following message with I fill the path to .wav files in ```wav_file_1``` and ```wav_file_2``` arguments. 
```C:\...\mcd\mcd_computation.py:318: FutureWarning: Pass y=[...] as keyword args. From version 0.10 passing these as positional arguments will result in an error```
Could this warning be avoid?

**Comment by stefantaubert** [comment]
Thanks for the information about the warning. We've updated the code significantly and now the warning is not present anymore. We published the package to [PyPI](https://pypi.org/project/mel-cepstral-distance/), you can install it via `pip install mel-cepstral-distance`.

**Comment by jasminsternkopf** [comment]
I don't remember exactly on which documents we based the default arguments, but I think the values for hop_length and n_mels are from Kubichek's paper, and we took some inspiration from the paper "Voice Recognition Algorithms using Mel
Frequency Cepstral Coefficient (MFCC) and
Dynamic Time Warping (DTW) Techniques" (like the usage of hamming windows).

**Comment by chankl3579** [comment]
Thanks for the code update and the info! Will check the papers.
